version: '3.8'
services:
  nest-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api
    restart: always
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=prod
      - PATH=/usr/local/lib/node_modules/pm2/bin:$PATH
    depends_on:
      - nest-redis
    env_file:
      - ./env/.prod.env

  nest-redis:
    image: redis:6.2.6-alpine
    container_name: nest-redis
    restart: always
    command: redis-server
    ports:
      - 6379:6379
    expose:
      - 6379

  nest-nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - nest-api
